### ISSUE TITLE
AttributeError: 'module' object has no attribute 'autocommit'

### ISSUE THREAD

**Issue by mhassan1991** [lilspikey/django-background-task#15]
When running 'python manage.py' after adding background-task in installed apps, I am getting following error 'AttributeError: 'module' object has no attribute 'autocommit'.
'

**Comment by johnsensible** [comment]
Which version of Django are you using?

I've not yet merged in a pull request to get things working on Django 1.7 (https://github.com/lilspikey/django-background-task/pull/12) which may well fix this.

**Comment by mhassan1991** [comment]
Django 1.8

**Comment by mhassan1991** [comment]
@johnsensible 
Have you merged pull request?

**Comment by johnsensible** [comment]
Sorry no.  Very busy at the moment.  Will try to get it sorted soon though.

**Comment by ravigadila** [comment]
Hello,  @johnsensible
Is this issue solved or not..!

**Comment by johnsensible** [comment]
It should be working if you use the code from that pull request.  However I've not had time to review that pull request and merge it in properly (mostly as I've not had any projects using Django 1.7 and django background task).

**Comment by IRIP** [comment]
та же проблема на django2 !
